---
all:
  hosts:
    nexus-01:
      ansible_host: <your_nexus_host>
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: <your_username>
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'